name: fl_bustter
description: A flexible CQRS-style message bus and validation package for Dart & Flutter.
version: 1.0.0

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
