name: fl_bustter
description: A flexible CQRS-style message bus and validation package for Dart & Flutter.
version: 1.0.0

homepage: https://github.com/Mbouziani/fl_bustter
repository: https://github.com/Mbouziani/fl_bustter
issue_tracker: https://github.com/Mbouziani/fl_bustter/issues
documentation: https://github.com/Mbouziani/fl_bustter#readme


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


# Optional but useful
topics:
  - cqrs
  - validation
  - bus
  - flutter
  - dart